### ISSUE TITLE
Use frp instead of ngrok 1.0

### ISSUE THREAD

**Issue by DewitteRuben** [RecordEvolution/DeviceManagementAgent#104]

**Comment by markope** [comment]
Now that you are almost done, how hard would it be to include user authentication into the tunnel usage?

i.e. 

When a user uses a tunnel we check if he is logged in to the platform and allow access based on his privileges on the swarm / device. So only invited users can use the tunnel and not everyone. That should be possible with http(s) tunnels, because we can use the user's cookies in browsers to validate. For UDP probably not possible and for TCP I don't know.

This is just a question ;)
